name: "validate"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: "Validate ontology"
    runs-on: "ubuntu-latest"
    container: ghcr.io/niegrzybkowski/ci-worker-test:main

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          path: opencs

      - name: "Validate ontology with SHACL"
        run: bash /app/validate_jena.sh
